### ISSUE TITLE
애니메이션 GIF를 이미지 업로드시 PNG로 저장되는 문제 

### ISSUE THREAD

**Issue by SightStudio** [TASK-FORCE/mannalga-front-app#256]
다음과 같이 애니메이션 GIF를 올릴때 Cropper가 PNG로 변경해서 저장하는듯하네요
애니메이션 gif의 경우 cropper를 무시하도록..? 해야할 것같네요

![image](https://user-images.githubusercontent.com/50672087/115041132-250e0880-9f0d-11eb-8057-713ef6a684b4.png)

올렸던 사진 
![junior](https://user-images.githubusercontent.com/50672087/115041141-28a18f80-9f0d-11eb-83c7-0e29f235cbd7.gif)

**Comment by pompitzz** [comment]
@SightStudio 

png로 저장되는건 제가 하드코딩을 해놔서 그런거였네요 ㅎㅎ.
gif로 저장하게 변경해도 cropper를 적용하면 고정된 이미지로 저장되어서 png, jpeg만 cropper를 사용하도록 변경하였습니다.

gif로 사진첩 저장을 하게되면 레이턴시가 14s정도 걸리는데 확인 가능하실까요?
![image](https://user-images.githubusercontent.com/57207769/115105046-6cd97200-9f97-11eb-92f4-431cca906999.png)

### 사용된 이미지
![giftest](https://user-images.githubusercontent.com/57207769/115105049-6fd46280-9f97-11eb-8487-3c949c6ee6b9.gif)

**Comment by SightStudio** [comment]
이부분은 gif에서 webp로 변경하는 부분이 생각보다 오래걸리네요 이부분은 비동기로 처리하는게 낫겠네요

**Comment by pompitzz** [comment]
@SightStudio 
네. 프론트는 해결되었으니 티켓 닫을게요.
적용 후 톡으로 공유부탁드려요.
