### ISSUE TITLE
댓글 삭제와 관련된 UI 수정 요청

### ISSUE THREAD

**Issue by yyy9942** [TASK-FORCE/mannalga-front-app#257]
현재 댓글 삭제시 soft delete가 아닌, 실제 데이터베이스 내부 삭제를 하고있습니다.
하지만 이 구조로 가게된다면 대댓글이 있는 댓글을 삭제할 때 문제가 됩니다.
상위 댓글을 삭제했을때도 하위 댓글 데이터는 모두 남기고싶으니, 하위 대댓글이 있을 때 삭제한 댓글은 deleteFlag를 true 로 주어 '삭제된 댓글입니다'형식으로 보여주고자 합니다.

댓글데이터는 모두 동일하게 들어갑니다만, 추가로 들어가는 **deleteFlag가 true일 경우 아래와 같이 색상을 변경하였으면 좋겠습니다.**

deleteFlag를 추가로 넣는 과정은 @SightStudio 가 진행해주시고 있습니다. 

![image](https://user-images.githubusercontent.com/46917538/115098585-c9269c80-9f6b-11eb-89ef-797de21518b3.png)

![image](https://user-images.githubusercontent.com/46917538/115098668-3c301300-9f6c-11eb-9518-6e3c5a354eb6.png)

cc. @030ii

**Comment by pompitzz** [comment]
@yyy9942 
삭제된 상위 댓글이 하위 댓글을 가진다면 deleteFlag를 true로 내려주고, 삭제된 상위 댓글이 하위 댓글을 가지지 않으면 해당 댓글은 내려오지 않게되나요?

**Comment by yyy9942** [comment]
@pompitzz 
하위댓글과는 관계없이 다 내려줄듯합니다.

@SightStudio

**Comment by pompitzz** [comment]
삭제된 상위 댓글이 하위 댓글을 가지지 않으면 해당 상위 댓글을 내려주지 않는게 좋을 거 같아요.

1. 프론트에서 deleteFlag가 true인데 하위 댓글이 있으면 댓글을 보여주고, 없으면 보여주지 않는 로직을 가지는건 좋지 않다고 생각합니다.
2. 댓글을 페이징으로 20개씩 조회하는데 만약 다수의 댓글이 삭제된 댓글이고 하위 댓글을 가지지 않으면 해당 댓글들은 보여지지 않아야 하기때문에 실제로 프론트에선 댓글 리스트를 조회하더라도 삭제되지 않은 소수의 댓글만 추가되거나 아예 추가되지 않을 수도 있어요.

**Comment by yyy9942** [comment]
저도 페이징과 같은 이슈로, 삭제된 댓글을 모두 내려주는 것으로 생각하고 있는데요. 삭제시 댓글을 숨기는게아니라 내용정도만 삭제된 댓글이라 표시해주는 것으로 생각하고 있습니다.


@SightStudio 
삭제된 댓글중 하위댓글이 없는 대상을 제외하려면 페이징을 변경하여야하는데요, 어떻게하는게 좋을까요?

**Comment by SightStudio** [comment]
```
삭제된 상위 댓글이 하위 댓글을 가지지 않으면 해당 상위 댓글을 내려주지 않는게 좋을 거 같아요.
```

> 저도 이부분은 서버에서 처리하는게 맞다고 생각합니다

```
삭제된 댓글중 하위댓글이 없는 대상을 제외하려면 페이징을 변경하여야하는데요, 어떻게하는게 좋을까요?
```
> 이부분은 처리가 매끄럽지는 않지만, 자식 댓글이 있을 경우 delete flag로 soft delete 시키고, 
자식 댓글이 없는 경우 실제 row를 delete 시켜서 해결할 수 있겠네요 

그래도 결국 색을 다르게 해주거나 삭제된 된 댓글에는 댓글을 달 수 없도록 프론트에서 처리하기 위해 (백엔드에서도 처리함)
delete flag를 내려주긴 해야할것 같네요 

@yyy9942 
@pompitzz

**Comment by pompitzz** [comment]
네. 그럼 프론트에서는 deleteFlag가 true면 아래와 같이 적용하고, 하위 댓글이 없는 케이스는 따로 고려하지 않겠습니다.
1. contnet를 `삭제된 댓글입니다` 로 변경
2. 하위 댓글 작성 불가

**Comment by SightStudio** [comment]
@pompitzz 

```
1. contnet를 삭제된 댓글입니다 로 변경
```

> 이부분은 텍스트 자체는 서버에서 변경해줘서 내려줄 예정이라 text 색만 변경해주시면 될것같아요

**Comment by pompitzz** [comment]
넵. deleteFlag 필드명은 어떤거로 하실 예정이신가요?

**Comment by SightStudio** [comment]
isDeleted로 하면 될것같네요 ㅎㅎ

**Comment by pompitzz** [comment]
프론트는 적용되었으므로 티켓 닫을게요. 백엔드 적용되면 톡으로 공유부탁드립니다.
