### ISSUE TITLE
App name 변경 요청

### ISSUE THREAD

**Issue by yyy9942** [TASK-FORCE/mannalga-front-app#260]
@pompitzz 
웹사이트로 접속하면 상단 바에 super-front라고 보이고 있습니다.
![image](https://user-images.githubusercontent.com/46917538/115117628-87810a80-9fda-11eb-9d8c-9e8ad1ca3819.png)

이를 Mannalga 로 변경부탁드립니다.

**Comment by pompitzz** [comment]
반영되었습니다~
