### ISSUE TITLE
오픈 후 처리 - 디버깅

### ISSUE THREAD

**Issue by 030ii** [TASK-FORCE/mannalga-front-app#265]
### 디자인 이슈
- [ ] html 태그도 background color를 테마 색상과 동일하게 처리 가능할까요?
(테마 상관없이 화면을 옆으로 밀면 html태그의 기본색 #ffffff가 나오고있어요. 사진은 red로 바꿨을때 화면입니다)
![image](https://user-images.githubusercontent.com/7741589/115151573-6a1a7200-a0a8-11eb-9161-2b688468577b.png)

**Comment by pompitzz** [comment]
확인 감사합니다. 해당 이슈 처리되었습니다~
